name: bit
on:
  push:
    paths:
      - .github/workflows/bit.yml
      - "dockerfiles/bit/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/bit.yml
      - "dockerfiles/bit/**"
      - .github/workflows/reusable.yml

jobs:
  bit:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: bit
      version: v1.1.2
