name: go-outline
on:
  push:
    paths:
      - .github/workflows/go-outline.yml
      - "dockerfiles/go-outline/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/go-outline.yml
      - "dockerfiles/go-outline/**"
      - .github/workflows/reusable.yml

jobs:
  go-outline:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: go-outline
      version: 9736a4b
