name: gomock
on:
  push:
    paths:
      - .github/workflows/gomock.yml
      - "dockerfiles/gomock/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/gomock.yml
      - "dockerfiles/gomock/**"
      - .github/workflows/reusable.yml

jobs:
  gomock:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: gomock
      version: v1.6.0
