name: gopkgs
on:
  push:
    paths:
      - .github/workflows/gopkgs.yml
      - "dockerfiles/gopkgs/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/gopkgs.yml
      - "dockerfiles/gopkgs/**"
      - .github/workflows/reusable.yml

jobs:
  gopkgs:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: gopkgs
      version: v2.1.2
