name: goplay
on:
  push:
    paths:
      - .github/workflows/goplay.yml
      - "dockerfiles/goplay/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/goplay.yml
      - "dockerfiles/goplay/**"
      - .github/workflows/reusable.yml

jobs:
  goplay:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: goplay
      version: v1.0.0
