name: gotests
on:
  push:
    paths:
      - .github/workflows/gotests.yml
      - "dockerfiles/gotests/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/gotests.yml
      - "dockerfiles/gotests/**"
      - .github/workflows/reusable.yml

jobs:
  gotests:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: gotests
      version: v1.6.0
