name: logo-ls
on:
  push:
    paths:
      - .github/workflows/logo-ls.yml
      - "dockerfiles/logo-ls/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/logo-ls.yml
      - "dockerfiles/logo-ls/**"
      - .github/workflows/reusable.yml

jobs:
  logo-ls:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: logo-ls
      version: v1.3.7
