name: mockgen
on:
  push:
    paths:
      - .github/workflows/mockgen.yml
      - "dockerfiles/mockgen/**"
  pull_request:
    paths:
      - .github/workflows/mockgen.yml
      - "dockerfiles/mockgen/**"

jobs:
  verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Build image
        run: docker build dockerfiles/mockgen

  publish:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=version::v1.6.0
          echo ::set-output name=platforms::linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x,linux/riscv64
          echo ::set-output name=created::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo ::set-output name=revision::$(git rev-parse --short HEAD)

      - name: Build and push final image
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/mockgen
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
            CREATED=${{ steps.vars.outputs.created }}
            REVISION=${{ steps.vars.outputs.revision }}
          tags: |
            qmcgaw/binpot:mockgen
            qmcgaw/binpot:mockgen-${{ steps.vars.outputs.version }}
          push: true
