name: supervisord
on:
  push:
    paths:
      - .github/workflows/supervisord.yml
      - "dockerfiles/supervisord/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/supervisord.yml
      - "dockerfiles/supervisord/**"
      - .github/workflows/reusable.yml

jobs:
  supervisord:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: supervisord
      version: v0.7.3
